---
NCBI_username: username 
NCBI_password: password
NCBI_ftp_host: 'sftp-private.ncbi.nlm.nih.gov'
NCBI_API_URL: 'https://submit.ncbi.nlm.nih.gov/api/2.0/files/FILE_ID/?format=attachment'
BioSample_package: "Pathogen.cl.1.0"
table2asn_email: 'gb-admin@ncbi.nlm.nih.gov'
# tbl2asn_flags: -M n -Z -J -c w
Description:
  Title:  Test
  Comment: This is a test submission
  Organization:
    '@role': owner
    '@type': institute
    '@org_id': 30206
    Name: CDC
    Address:
      Affil: CDC
      Div: DHCPP-PRB
      Street: 1600 Clifton Rd
      City: Atlanta
      State: GA
      Postal_code: 30329
      Country: USA
      Email: test@cdc.gov
      Phone: ""
    Submitter:
      '@email': test9@cdc.gov
      '@alt_email': test@cdc.gov
      Name:
        First: John
        Last: Doe
GISAID_client-id: TEST-EA76875B00C3
GISAID_username: username
GISAID_password: password